### ISSUE TITLE
repo 이름에 대한 건의

### ISSUE THREAD

**Issue by lexiconium** [DoubleJONY/KDJ-algorithm-programmers#177]
1. 사실 처음부터 KDJ은 아무 연관이 없었음
2. 스터디가 진행되며 이제는 programmers 뿐만 아니라 boj, leetcode 등의 문제 또한 풀이했음

따라서 적절한 repo 명으로 변경하는게 어떤지 건의해봅니다.

추신. 의중, 18 주차 java 풀이 어서 커밋해주시죠 XD

**Comment by heoh** [comment]
동의합니다.
KDJ는 팀명으로 인식할 수도 있을 것 같습니다. (좋은 대체 이름이 생각나지 않네요.)

**Comment by DoubleJONY** [comment]
개인 repo 에 KDJ 라는 팀명 상징을 대체할 다른 이름은 나중에 다시 정하여 수정하도록 합니다.
programmers 명칭은 challenge 로 변경합니다.
